services:
  frontend:
    build: .
    container_name: mm_frontend
    hostname: frontend
    network_mode: "host"            #uncomment for multi-machine (true distributed)
    environment:
      - DISCOVERY=1
      - MODE=mpi
      - DATA_DIR=/data
      - NUM_PROCS=3
    volumes:
      - ./matrices:/data:rw
   # networks:                     #comment for multi-machine (true distributed)
   #   - matrixnet

  worker:
    build: .
    container_name: mm_worker
    hostname: worker
    network_mode: "host"            #uncomment for multi-machine (true distributed)
    environment:
      - DISCOVERY=1
      - MODE=mpi
      - DATA_DIR=/data
   # networks:                     #comment for multi-machine (true distributed)
   #   - matrixnet

  linear:
    build: .
    container_name: mm_linear
    environment:
      - MODE=linear
      - DATA_DIR=/data
    volumes:
      - ./matrices:/data:rw

  mt:
    build: .
    container_name: mm_mt
    environment:
      - MODE=mt
      - DATA_DIR=/data
    volumes:
      - ./matrices:/data:rw

networks:
  matrixnet:
    driver: bridge